/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package diagrams-0.0.0 */
#ifndef VERSION_diagrams
#define VERSION_diagrams "0.0.0"
#endif /* VERSION_diagrams */
#ifndef MIN_VERSION_diagrams
#define MIN_VERSION_diagrams(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_diagrams */
/* package base-4.19.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.19.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package diagrams-contrib-1.4.5.1 */
#ifndef VERSION_diagrams_contrib
#define VERSION_diagrams_contrib "1.4.5.1"
#endif /* VERSION_diagrams_contrib */
#ifndef MIN_VERSION_diagrams_contrib
#define MIN_VERSION_diagrams_contrib(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_VERSION_diagrams_contrib */
/* package diagrams-lib-1.4.6.2 */
#ifndef VERSION_diagrams_lib
#define VERSION_diagrams_lib "1.4.6.2"
#endif /* VERSION_diagrams_lib */
#ifndef MIN_VERSION_diagrams_lib
#define MIN_VERSION_diagrams_lib(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 6)
#endif /* MIN_VERSION_diagrams_lib */
/* package diagrams-svg-1.4.4 */
#ifndef VERSION_diagrams_svg
#define VERSION_diagrams_svg "1.4.4"
#endif /* VERSION_diagrams_svg */
#ifndef MIN_VERSION_diagrams_svg
#define MIN_VERSION_diagrams_svg(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_diagrams_svg */
/* package lens-5.3.4 */
#ifndef VERSION_lens
#define VERSION_lens "5.3.4"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  3 || \
  (major1) == 5 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_lens */

/* tool gcc-17.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "17.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  17 || \
  (major1) == 17 && (major2) <  0 || \
  (major1) == 17 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.30.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.30.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.0.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.0.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "diagrams-0.0.0-K8ileCWufRH4490n3REtN-diagrams-exe"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
